### PR TITLE
Added code changes to display Summary widget in Home screen

### PR DESCRIPTION
**Pull request by poojts**
1. Modified Index page of home.
2. Added new folder containing summary widget code

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Hi, @poojts, Do I need to do something specific to view the Summary dashboard on the home page? I switched my local frontend instance to this branch, I'm seeing only Mapping Contributor Data and Publication Date Timeline. Please let me know. Thanks.

**Comment by poojts** [comment]
Hi Sandeep,

There is no changes needed to view the widget. I will check the issue and
let you know.

Thanks, and Regards,
Pooja

**Comment by sandeep-ps** [comment]
When reviewing this PR, I was using the backend branch related to word cloud, if that helps. I will try with the develop branch later.

Sent from my mobile

Best regards,
Sandeep

On May 9, 2024, at 4:20 PM, Pooja Shashidhar ***@***.***> wrote:

﻿

Hi Sandeep,

There is no changes needed to view the widget. I will check the issue and
let you know.

Thanks, and Regards,
Pooja

**Comment by sandeep-ps** [comment]
I see that other widgets have corresponding models in https://github.com/htrc/torchlite-backend/tree/develop/htrc/torchlite/widgets. Does Summary widget needs to have something similar? Or if it needs to be add to a dashboard, please let me know how it's done. Thanks.

**Comment by poojts** [comment]
Hai Sandeep ,

I am able to see the widget in my local branch.
I have not added any model in the widget folder. Can you please change your
branch to my development branch and check once.

Thanks & Regards,
Pooja

**Comment by dkudeki** [comment]
@poojts Widgets need a component in both the frontend and backend repos. The retrieval and processing of data from the EF-API should be happening on the backend, especially when the widget handles features data. I've taken the fetchDataFromAPI() function here which handles that logic, and reimplemented it in the python backend here: https://github.com/htrc/torchlite-backend/blob/summary/htrc/torchlite/widgets/summary.py in a branch built to associate with these frontend changes.

It looks to me like you probably started building this before David did some major refactors, so I've made some updates to integrate those changes. It looks close to being ready. I had to add some stuff for the detailed view including converting the data in to a table/CSV that you might have opinions on. The main issue I see right now is that I'm having trouble generating a PNG version of the widget to download

**Review by dkudeki — APPROVED** [review]

**Pull request merged**
